# -*- coding: utf-8 -*-
"""lab7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VzR0C7s3UBuNJgmxPaAviWN7WFZU36l_
"""

my_tuple = tuple(input('Enter space-separated words: ').split())

print(my_tuple)

from google.colab import files

files.download("lab7.ipynb")